---
- name: playscope variables
  hosts: all
  become: yes
  gather_facts: false
  vars:
    - a: jo
    - b: password
    - c: /tmp/jo
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
